// Google + Meta + xAI + Mistral 发布数据（经独立研究 agent 多源核实，2026-07-06）
import type { Release } from "./data"

export const RELEASES_GMXM: Release[] = [
  // ===== Google =====
  {
    vendor: "google", date: "2024-02", name: "Gemini 1.5 Pro", tier: "major",
    headline: "百万上下文 MoE 开山之作",
    architecture: "Google 官方确认采用稀疏 MoE 架构（参数量未披露）。上下文 128K 起步、开发者可用 1M（后扩至 2M），实验中演示 10M。原生多模态（文本/图像/音频/视频），TPU 集群训练。",
    archClaim: "事实",
    capability: "1M 上下文「大海捞针」召回率 >99%，长上下文能力当时断层领先。MMLU 81.9%，综合接近 Gemini 1.0 Ultra 但推理成本大幅降低。",
    capClaim: "事实",
    price: "发布时 $3.50/$10.50（≤128K），2024-10 降至 $1.25/$5",
    compute: "闭源。TPU v4/v5 集群训练（官方确认），具体规模与 token 量未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "google", date: "2024-05", name: "Gemini 1.5 Flash", tier: "minor",
    headline: "在线蒸馏轻量旗舰",
    architecture: "从 1.5 Pro 在线蒸馏（online distillation）得到的轻量稠密模型（官方论文确认）。保留 1M 上下文与全模态输入。",
    archClaim: "事实",
    capability: "MMLU 78.9%，接近 1.5 Pro 的多数能力但延迟/成本大幅下降，成为 Google 高量级 API 流量主力。",
    capClaim: "事实",
    price: "降价后 $0.075/$0.30（≤128K），当时业界最便宜的 1M 上下文模型",
    compute: "闭源。TPU 训练；蒸馏自 1.5 Pro。",
    computeClaim: "事实",
  },
  {
    vendor: "google", date: "2024-06", name: "Gemma 2 (9B/27B)", tier: "minor",
    headline: "开源蒸馏小钢炮",
    architecture: "9B/27B 稠密 Transformer，交替使用滑动窗口注意力与全局注意力，8K 上下文。9B 用知识蒸馏训练，27B 从头训练。",
    archClaim: "事实",
    capability: "27B MMLU 75.2%、LMArena Elo ~1218，以 1/2.5 的参数量击败 Llama 3 70B，当时开源同尺寸最强之一。",
    capClaim: "事实",
    price: "开源免费，Gemma 自定义 license（允许商用，非 Apache）",
    compute: "开放权重。TPU v5p 训练，27B 用 13T tokens（官方技术报告）。",
    computeClaim: "事实",
  },
  {
    vendor: "google", date: "2024-12", name: "Gemini 2.0 Flash", tier: "major",
    headline: "原生智能体时代开场",
    architecture: "第二代架构首发型号：原生工具调用、原生多模态输出（图像/语音生成）实验能力，1M 上下文。官方确认在第六代 TPU Trillium 上训练与推理。",
    archClaim: "事实",
    capability: "以 Flash 定位全面超过 1.5 Pro 且速度约 2 倍：MMLU-Pro 76.4%、GPQA 62.1%、Natural2Code 92.9%。为 Project Astra/Mariner 等 agent 原型提供底座。",
    capClaim: "事实",
    price: "GA（2025-02）$0.10/$0.40",
    compute: "闭源。100% 在 Trillium（TPU v6e）上训练，Google 部署超 10 万片 Trillium 集群；FLOPs 未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "google", date: "2025-03", name: "Gemini 2.5 Pro", tier: "major", preview: true,
    headline: "思考模型登顶竞技场",
    architecture: "Google 首个默认带「thinking」的旗舰，稀疏 MoE + 推理时思维链。1M 上下文（宣称将扩 2M），全模态输入。",
    archClaim: "事实",
    capability: "发布即 LMArena 第一（Elo ~1443，领先第二名近 40 分）；GPQA Diamond 84.0%、AIME 2025 86.7%（无工具）、SWE-bench Verified 63.8%。",
    capClaim: "事实",
    price: "$1.25/$10（≤200K），$2.50/$15（>200K）",
    compute: "闭源。TPU（v5p/Trillium 世代）训练，规模未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "google", date: "2025-03", name: "Gemma 3 (1B–27B)", tier: "minor",
    headline: "单卡可跑的多模态开源",
    architecture: "1B/4B/12B/27B 稠密，4B 以上带 SigLIP 视觉编码器，128K 上下文，140+ 语言。局部/全局注意力 5:1 交替以压 KV cache。",
    archClaim: "事实",
    capability: "27B LMArena Elo ~1338 进入前十，以单 H100 可跑的成本逼近 DeepSeek-V3 级体验；MMLU-Pro 67.5%。",
    capClaim: "事实",
    price: "开源免费，Gemma license",
    compute: "开放权重。TPU 训练，27B 用 14T tokens（官方披露），并用蒸馏。",
    computeClaim: "事实",
  },
  {
    vendor: "google", date: "2025-04", name: "Gemini 2.5 Flash", tier: "minor", preview: true,
    headline: "可调思考预算混合模型",
    architecture: "首个「hybrid reasoning」Flash：开发者可开关 thinking 并设置思考 token 预算。1M 上下文，全模态输入。",
    archClaim: "推理",
    capability: "预览版 LMArena 位列第二，仅次于 2.5 Pro；GPQA ~78%、AIME 2025 ~78%（开思考）。性价比档位的推理能力首次接近上代旗舰。",
    capClaim: "事实",
    price: "GA（2025-06）$0.30/$2.50",
    compute: "闭源。TPU 训练，规模未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "google", date: "2025-11", name: "Gemini 3 Pro", tier: "major",
    headline: "首破 1500 Elo 的多模态之王",
    architecture: "稀疏 MoE，1M 输入/64K 输出，原生全模态，附带 Deep Think 深度推理模式。架构细节未披露；随 Antigravity 智能体平台同发（2025-11-18）。",
    archClaim: "推测",
    capability: "LMArena 1501 Elo（史上首破 1500）；HLE 37.5%、GPQA Diamond 91.9%、AIME 2025 95%（无工具）、SWE-bench Verified 76.2%、ARC-AGI-2 31.1%。",
    capClaim: "事实",
    price: "$2/$12（≤200K），$4/$18（>200K）",
    compute: "闭源。TPU 集群训练（Ironwood 世代前后），规模未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "google", date: "2025-12", name: "Gemini 3 Flash", tier: "minor",
    headline: "编码超越自家 Pro",
    architecture: "Gemini 3 家族速度档，1M 上下文，全模态输入，可配置 thinking level。12-17 发布，成为 Gemini App 默认并进入 Gemini CLI。",
    archClaim: "事实",
    capability: "SWE-bench Verified 78%（反超 Gemini 3 Pro 的 76.2%）、GPQA Diamond 90.4%、HLE 33.7%；Artificial Analysis 测其超 2.5 Pro 且快 3 倍。",
    capClaim: "事实",
    price: "$0.50/$3（音频输入 $1）",
    compute: "闭源。TPU 训练，规模未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "google", date: "2026-02", name: "Gemini 3.1 Pro", tier: "major",
    headline: "ARC-AGI-2 翻倍碾压",
    architecture: "Gemini 3 Pro 的核心智能升级版（Deep Think 底座即此模型），1M 上下文，全模态。架构未披露。2026-02-19 发布。",
    archClaim: "推测",
    capability: "ARC-AGI-2 77.1%（经 ARC Prize 验证，较 3 Pro 的 31.1% 翻倍以上）；GPQA Diamond 94.3%（当时最高）、HLE 44.4%、SWE-bench Verified 80.6%、Terminal-Bench 2.0 68.5%。AA 智能指数 57 居首。",
    capClaim: "事实",
    price: "$2/$12（与 3 Pro 相同；注意不是 $2.5/$15）",
    compute: "闭源。TPU 训练，规模未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "google", date: "2026-05", name: "Gemini 3.5 Flash", tier: "major",
    headline: "涨价 3 倍的全能主力",
    architecture: "I/O 2026（05-19/20）发布的新一代 Flash，定位「用它跑一切」的主力模型。1M 上下文、全模态、可调思考。架构未披露。",
    archClaim: "推测",
    capability: "Terminal-Bench 2.1 76.2%，agentic/终端操作大幅跃升；官方称多数任务超上代 Pro。定价较 Gemini 3 Flash 涨 3 倍，被 Simon Willison 等评为「廉价 AI 时代终结」的标志。",
    capClaim: "事实",
    price: "$1.50/$9（Gemini 3 Flash 的 3 倍；成本敏感用户被导向 3.1 Flash-Lite）",
    compute: "闭源。TPU（Ironwood 世代）训练，规模未披露。",
    computeClaim: "推测",
  },

  // ===== Meta =====
  {
    vendor: "meta", date: "2024-04", name: "Llama 3 (8B/70B)", tier: "major",
    headline: "15T tokens 开源新标杆",
    architecture: "8B/70B 稠密 Transformer，GQA 注意力，8K 上下文，128K 词表 tokenizer。纯文本。",
    archClaim: "事实",
    capability: "70B-Instruct MMLU 82.0%、HumanEval 81.7%，发布时开源最强，LMArena 英文榜一度并列 GPT-4 级。",
    capClaim: "事实",
    price: "开源免费，Llama Community License（>7 亿 MAU 需单独授权）",
    compute: "开放权重。两个 24k H100 集群训练，>15T tokens（官方披露）。",
    computeClaim: "事实",
  },
  {
    vendor: "meta", date: "2024-07", name: "Llama 3.1 405B", tier: "major",
    headline: "首个开源前沿级巨模",
    architecture: "405B 稠密 Transformer（刻意不用 MoE 以保训练稳定），128K 上下文，GQA。同发 8B/70B 升级版。",
    archClaim: "事实",
    capability: "MMLU 88.6%、GPQA 51.1%、HumanEval 89.0%，首个与 GPT-4o/Claude 3.5 Sonnet 同档的开放权重模型。",
    capClaim: "事实",
    price: "开源免费，Llama Community License",
    compute: "开放权重。~16,000 H100，15.6T tokens，约 3.8e25 FLOPs（论文披露），FP8 推理优化。",
    computeClaim: "事实",
  },
  {
    vendor: "meta", date: "2024-09", name: "Llama 3.2 (1B–90B)", tier: "minor",
    headline: "端侧+视觉补全布局",
    architecture: "1B/3B 纯文本端侧模型（128K 上下文，蒸馏+剪枝自 8B）；11B/90B 视觉模型采用 adapter 式跨注意力接入图像编码器，不动原语言权重。",
    archClaim: "事实",
    capability: "90B-Vision MMMU ~60.3、DocVQA 90.1，对标 Claude 3 Haiku/GPT-4o-mini 级视觉；1B/3B 主打手机端推理。",
    capClaim: "事实",
    price: "开源免费，Llama Community License（欧盟对视觉版有使用限制）",
    compute: "开放权重。基于 3.1 底座继续训练，增量算力未披露。",
    computeClaim: "推理",
  },
  {
    vendor: "meta", date: "2024-12", name: "Llama 3.3 70B", tier: "minor",
    headline: "70B 跑出 405B 性价比",
    architecture: "70B 稠密，纯文本，128K 上下文，与 3.1 70B 同架构，靠后训练（在线偏好优化等）提升。",
    archClaim: "事实",
    capability: "MMLU 86.0%、IFEval 92.1%、HumanEval 88.4%，多数任务逼近 405B，推理成本约其 1/6。",
    capClaim: "事实",
    price: "开源免费，Llama Community License",
    compute: "开放权重。复用 3.1 预训练底座，仅新增后训练算力。",
    computeClaim: "事实",
  },
  {
    vendor: "meta", date: "2025-04", name: "Llama 4 Scout/Maverick", tier: "major",
    headline: "MoE+10M 上下文的滑铁卢",
    architecture: "Meta 首代 MoE：Scout 109B 总参/17B 激活/16 专家，iRoPE 交替注意力，宣称 10M 上下文；Maverick 400B 总参/17B 激活/128 专家，1M 上下文。原生多模态（早期融合）。",
    archClaim: "事实",
    capability: "Maverick 官方报 LMArena Elo 1417，但被曝提交「实验性对话优化版」引发刷榜争议；发布版实测明显缩水。旗舰 Behemoth（~2T 总参/288B 激活）多次跳票后被搁置，团队大改组。",
    capClaim: "事实",
    price: "开源免费，Llama 4 Community License（7 亿 MAU 上限，欧盟受限）",
    compute: "开放权重。Scout 训练 ~40T tokens、Maverick ~22T；Behemoth 曾用 32k GPU FP8 训练（官方博客披露）。",
    computeClaim: "事实",
  },
  {
    vendor: "meta", date: "2026-04", name: "Muse Spark", tier: "major",
    headline: "弃开源转闭源的豪赌",
    architecture: "Meta Superintelligence Labs（Alexandr Wang 领衔）9 个月重构 AI 栈后的首个模型，04-08 发布。闭源闭权重，架构/参数完全未披露——Meta 开源路线的历史性转向（Bloomberg 确认），Llama 5 未发布。",
    archClaim: "推测",
    capability: "AA 智能指数 52，总排第四（GPT-5.4/Gemini 3.1 Pro 57、Opus 4.6 53）；HealthBench Hard 42.8 居首；但 SWE-bench Verified 仅 59.0%，编码明显掉队。仅驱动 Meta AI 助手 + 少量私享 API 预览。",
    capClaim: "事实",
    price: "无公开 API 定价（仅 Meta AI 内置 + 私享预览）",
    compute: "闭源。训练集群未披露；背景是 Meta 2026 capex 指引 $115–135B、MSL 年烧钱约 $100 亿+（Bloomberg 估算）。",
    computeClaim: "推测",
  },

  // ===== xAI =====
  {
    vendor: "xai", date: "2024-03", name: "Grok-1（开源）", tier: "minor",
    headline: "314B MoE 权重裸奔开源",
    architecture: "314B 参数 MoE，8 专家/激活 2（~25% 参数激活），8K 上下文，纯文本 base 模型（未做对话微调），JAX+Rust 自研训练栈。",
    archClaim: "事实",
    capability: "MMLU 73%、HumanEval 63.2%（xAI 公布），约 GPT-3.5 到 Mixtral 之间水平；意义在于当时最大的开放权重模型。",
    capClaim: "事实",
    price: "开源免费，Apache 2.0（仅权重+推理代码）",
    compute: "开放权重。训练算力未披露（Colossus 之前的租用集群）。",
    computeClaim: "推测",
  },
  {
    vendor: "xai", date: "2024-08", name: "Grok-2", tier: "minor",
    headline: "追平第一梯队门票",
    architecture: "闭源（2025-08 才开源权重），架构未正式披露，带 FLUX 集成的图像生成入口，X 平台实时数据接入。",
    archClaim: "推测",
    capability: "LMArena（马甲 sus-column-r）当时冲到总榜前三；GPQA 56.0%、MMLU-Pro 75.5%、MATH 76.1%，首次让 xAI 摸到 GPT-4 级门槛。",
    capClaim: "事实",
    price: "API（grok-2-1212）$2/$10",
    compute: "闭源。Colossus 建成前训练，Musk 称用约 15–24k H100（口径不一）。",
    computeClaim: "推测",
  },
  {
    vendor: "xai", date: "2025-02", name: "Grok 3", tier: "major",
    headline: "20 万卡 Colossus 首秀",
    architecture: "闭源，带 Think/Big Brain 推理模式与 DeepSearch，1M 上下文（API 版 131K 起）。架构未披露。",
    archClaim: "推测",
    capability: "LMArena Elo 1402，首个破 1400 的模型；AIME 2025 93.3%（Think+cons@64）、GPQA Diamond 84.6%。xAI 称训练算力为 Grok 2 的 10 倍。",
    capClaim: "事实",
    price: "API（2025-04 开放）$3/$15；Grok 3 mini $0.30/$0.50",
    compute: "闭源。Colossus 集群：10 万 H100 于 122 天建成、后翻倍至 ~20 万卡（官方叙事）。",
    computeClaim: "事实",
  },
  {
    vendor: "xai", date: "2025-07", name: "Grok 4", tier: "major",
    headline: "RL 算力堆到预训练级",
    architecture: "闭源。xAI 称把强化学习算力提升到与预训练同一量级（RL at pretraining scale），原生工具调用+实时搜索融入推理链；Heavy 版多智能体并行。07-09 发布。",
    archClaim: "事实",
    capability: "HLE 25.4%（无工具）/ Heavy 带工具 44.4%；GPQA Diamond ~87–88%；ARC-AGI-2 15.9%（当时第一）；AIME 2025（Heavy）100%。",
    capClaim: "事实",
    price: "$3/$15（>128K 翻倍）；SuperGrok Heavy $300/月",
    compute: "闭源。Colossus ~20 万 GPU（H100/H200 混合，GB200 开始并网）训练。",
    computeClaim: "事实",
  },
  {
    vendor: "xai", date: "2025-11", name: "Grok 4.1 / 4.1 Fast", tier: "minor",
    headline: "情商与幻觉双修登顶",
    architecture: "闭源。主打对齐/人格/幻觉治理的后训练升级；4.1 Fast（11-19）提供 2M 上下文，当时业界最大。11-17 上线，比 Gemini 3 早一天登顶。",
    archClaim: "事实",
    capability: "LMArena Text Arena 1483 Elo 登顶（领先非 xAI 模型 31 分）；幻觉率 12.09%→4.22%；EQ-Bench3 1586 第一。次日被 Gemini 3（1501）反超。",
    capClaim: "事实",
    price: "Grok 4.1 Fast $0.20/$0.50（cached $0.05），2M 上下文",
    compute: "闭源。Colossus 集群后训练迭代，增量算力未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "xai", date: "2026-04", name: "Grok 4.3", tier: "major",
    headline: "最便宜的前沿推理模型",
    architecture: "闭源。1M 上下文，xAI 首个原生视频输入（视觉编码器直入），知识截止 2025-12。04-17 beta（与 SpaceX 收购 xAI 同日官宣）、04-30 开放 API、05 月初 GA。",
    archClaim: "事实",
    capability: "GDPval-AA Elo 1500（较上代 +321，超 Gemini 3.1 Pro/Muse Spark）；AA 智能指数 53；GPQA ~90%；但 SWE-bench Pro 落后 Claude Opus 4.7 两位数——定位从刷榜转向单位智能价格最优。",
    capClaim: "事实",
    price: "$1.25/$2.50（cached $0.20；>200K 输入计双倍）",
    compute: "闭源。Colossus/Colossus 2（Memphis，GB200 世代扩建）训练，规模未正式披露。",
    computeClaim: "推测",
  },

  // ===== Mistral =====
  {
    vendor: "mistral", date: "2024-04", name: "Mixtral 8x22B", tier: "minor",
    headline: "Apache 开源 SMoE 巅峰",
    architecture: "稀疏 MoE：141B 总参/39B 激活（8 专家选 2），64K 上下文，原生函数调用，多语言。",
    archClaim: "事实",
    capability: "MMLU 77.8%，当时 Apache 2.0 开源模型中性价比最优；数学/代码显著强于 Mixtral 8x7B。",
    capClaim: "事实",
    price: "开源免费 Apache 2.0；API $2/$6",
    compute: "开放权重。训练算力未披露（推测数千 H100 量级）。",
    computeClaim: "推测",
  },
  {
    vendor: "mistral", date: "2024-07", name: "Mistral Large 2", tier: "major",
    headline: "123B 稠密对标 405B",
    architecture: "123B 稠密 Transformer，128K 上下文，80+ 编程语言与多语言强化，单节点 H100 可推理为设计目标。",
    archClaim: "事实",
    capability: "MMLU 84.0%、HumanEval 92%、MATH 71.5%，以 1/3.3 参数量对标 Llama 3.1 405B；函数调用当时第一梯队。",
    capClaim: "事实",
    price: "权重开放但 MRL 研究许可（商用需付费）；API $2/$6",
    compute: "半开放（MRL license）。训练算力未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "mistral", date: "2025-05", name: "Mistral Medium 3", tier: "minor",
    headline: "8 倍降本打企业市场",
    architecture: "闭源（权重未放出，引发社区不满），多模态，128K 上下文，可 4 节点自托管部署。",
    archClaim: "事实",
    capability: "官方称达到 Claude 3.7 Sonnet 90%+ 水平而成本约 1/8；编码任务对标 GPT-4o 级。定位企业混合云。",
    capClaim: "事实",
    price: "$0.40/$2",
    compute: "闭源。训练算力未披露。",
    computeClaim: "推测",
  },
  {
    vendor: "mistral", date: "2025-06", name: "Magistral (Small/Medium)", tier: "minor",
    headline: "欧洲首个推理模型",
    architecture: "欧洲首个 reasoning 模型系。Small 24B（基于 Mistral Small 3）开源，Medium 闭源；纯 RLVR（可验证奖励强化学习）训练、无冷启动蒸馏，思维链可溯源、多语言推理。论文 arXiv:2506.10910。",
    archClaim: "事实",
    capability: "Medium AIME 2024 73.6%（maj@64 90%）、Small 70.7%；论文亮点是纯 RL 使 pass@1 提升 50%，且小模型纯 RL ≈ 蒸馏效果。1.2 版（2025-09）AIME24 达 91.8% 反超 DeepSeek-R1。",
    capClaim: "事实",
    price: "Small 开源免费 Apache 2.0（单卡 4090 可跑量化版）；Medium API $2/$5",
    compute: "Small 开放权重/Medium 闭源。RL 后训练为主，复用既有底座。",
    computeClaim: "事实",
  },
  {
    vendor: "mistral", date: "2025-12", name: "Mistral Large 3", tier: "major",
    headline: "675B MoE 回归 Apache",
    architecture: "重返前沿级稀疏 MoE：675B 总参/41B 激活（673B LLM + 2.5B 视觉编码器），256K 上下文，图文输入、40+ 语言，Apache 2.0。12-02 与 Ministral 3（14B/8B/3B）同发。",
    archClaim: "事实",
    capability: "LMArena 首发 Elo ~1418，开源非推理模型第 2；MMLU-Pro 73.1%、MATH-500 93.6%（独立评测）；但推理弱项明显（独立测 GPQA ~44%，与官方 67.2% 有争议）。",
    capClaim: "事实",
    price: "开源免费 Apache 2.0；API $0.50/$1.50",
    compute: "开放权重。3,000 张 NVIDIA H200 从头训练（官方披露）；GB200 NVL72 推理较 H200 提升 10 倍（NVIDIA 合作宣传）。",
    computeClaim: "事实",
  },
  {
    vendor: "mistral", date: "2026-03", name: "Mistral Small 4 (119B)", tier: "minor",
    headline: "6B 激活的全能 MoE",
    architecture: "MoE：119B 总参/6B 激活（128 专家选 4），256K 上下文，Pixtral 视觉编码器图文输入，per-request reasoning_effort 可调推理，FP8 权重、2×H200 免量化可跑。03-16 发布。",
    archClaim: "事实",
    capability: "开推理时对标/超越 GPT-OSS 120B 且输出短 3–4 倍；较 Small 3 延迟降 40%、吞吐 3 倍。发布初期工具调用生态未稳。",
    capClaim: "事实",
    price: "开源免费 Apache 2.0；API $0.15/$0.60",
    compute: "开放权重。训练算力未披露（NVIDIA 深度合作，Nemotron 联盟创始成员）。",
    computeClaim: "推测",
  },
]
