// DeepSeek + Qwen + Kimi 发布数据（技术报告透明，算力/成本多为事实级；经独立研究 agent 核实，2026-07-06）
import type { Release } from "./data"

export const RELEASES_CN: Release[] = [
  // ===== DeepSeek =====
  {
    vendor: "deepseek", date: "2024-05", name: "DeepSeek V2", tier: "major",
    headline: "MLA 开山之作，掀价格战",
    architecture: "236B 总参/21B 激活 MoE。首创 Multi-head Latent Attention（MLA），以低秩联合压缩把 KV cache 削减 93.3%，成为后续全系标配。DeepSeekMoE 细粒度专家：每层 2 共享 + 160 路由专家激活 6 个。128K 上下文，权重开源。",
    archClaim: "事实",
    capability: "MMLU 78.5、AlignBench 中文领先，能力约当时 Llama3-70B 档。真正冲击在成本端：API ¥1/¥2 per 1M 直接引爆 2024-05 国内大模型价格战，「AI 界拼多多」由此得名。",
    capClaim: "事实",
    price: "¥1/¥2 per 1M（约 $0.14/$0.28）；开源可自建",
    compute: "预训练 8.1T tokens，H800 集群。技术报告：相较自家 67B dense 节省 42.5% 训练成本、最大生成吞吐 5.76x。",
    computeClaim: "事实",
  },
  {
    vendor: "deepseek", date: "2024-09", name: "DeepSeek V2.5", tier: "minor",
    headline: "通用与代码双线合体",
    architecture: "架构与 V2 相同（236B/21B MoE、MLA、128K），将 V2-Chat 与 DeepSeek-Coder-V2 合并为单一模型对外。开源权重延续 V2 许可。",
    archClaim: "事实",
    capability: "官方口径：合并后 AlignBench、MT-Bench 与 HumanEval（≈89）均优于两个前身，通用对话与代码不再二选一。属产品线整合而非能力跃迁。",
    capClaim: "事实",
    price: "延续 V2 低价档 API；开源可自建",
    compute: "基于 V2/Coder-V2 权重的融合与继续训练，增量算力未单独披露。",
    computeClaim: "事实",
  },
  {
    vendor: "deepseek", date: "2024-12", name: "DeepSeek V3", tier: "major",
    headline: "$5.6M 训出 GPT-4o 级",
    architecture: "671B 总参/37B 激活。每层 1 共享 + 256 路由专家激活 8 个，auxiliary-loss-free 负载均衡；MLA + Multi-Token Prediction（MTP，含 14B MTP 模块共 685B）；业界首个大规模 FP8 混合精度训练成功案例。128K 上下文，权重开源（0324 版起转 MIT）。",
    archClaim: "事实",
    capability: "MMLU 88.5、MATH-500 90.2、LiveCodeBench 开源第一，整体与 GPT-4o/Claude 3.5 Sonnet 同档——开源阵营首次逼近闭源旗舰。MTP 后被 Qwen3-Next、Nemotron 3 等采纳成行业标配。",
    capClaim: "事实",
    price: "$0.27/$1.10（cache hit $0.07）；开源可自建",
    compute: "技术报告：14.8T tokens，2048 张 H800，全流程 2.788M H800-hours（预训练 2664K+长上下文 119K+后训练 5K）≈ $5.576M（@$2/GPU-h，不含研发）。FP8+MoE 稀疏+MTP 是省钱三件套——此数字成为出口管制下算力效率叙事的锚点。",
    computeClaim: "事实",
  },
  {
    vendor: "deepseek", date: "2025-01", name: "DeepSeek R1", tier: "major",
    headline: "开源推理，震动美股",
    architecture: "基于 V3-Base（671B/37B）做大规模强化学习（GRPO）。R1-Zero 证明不经 SFT 纯 RL 即可涌现自我反思等推理行为；正式版加冷启动数据+多阶段训练。MIT 许可，同步蒸馏 Qwen/Llama 系 1.5B–70B 六个小模型。",
    archClaim: "事实",
    capability: "AIME 2024 79.8%、MATH-500 97.3%、GPQA Diamond 71.5、Codeforces Elo 2029，全面对标 o1。发布一周引发 2025-01-27 Nvidia 单日 -17%——「中国算力效率冲击」的标志性事件。",
    capClaim: "事实",
    price: "$0.55/$2.19（cache hit $0.14）；开源自建 MIT",
    compute: "Nature 论文（2025-09）披露：R1 的 RL 阶段训练成本约 $294K（H800），叠加 V3 基座 $5.576M 合计仍不足 $6M。",
    computeClaim: "事实",
  },
  {
    vendor: "deepseek", date: "2025-08", name: "DeepSeek V3.1", tier: "major",
    headline: "混合推理，转向 Agent",
    architecture: "671B/37B（含 MTP 共 685B），单模型融合 thinking/non-thinking 双模式（特殊 token 切换），取代 V3+R1 双产品线。两阶段扩展上下文至 128K；权重采用 UE8M0 FP8 格式（适配国产芯片微缩放生态）。MIT，8-19 无预告直接上 HuggingFace。",
    archClaim: "事实",
    capability: "Aider 71.6% 略超 Claude Opus 4，SWE-bench Verified 66.0，思考模式效率高于 R1-0528。9-22 的 Terminus 版修补语言混杂并强化 Code/Search Agent。",
    capClaim: "事实",
    price: "$0.56/$1.68（cache hit $0.07）",
    compute: "基于 V3 base 续训：32K 阶段 630B + 128K 阶段 209B tokens，H800，增量算力远小于全量预训练。",
    computeClaim: "事实",
  },
  {
    vendor: "deepseek", date: "2025-12", name: "DeepSeek V3.2", tier: "major",
    headline: "DSA 稀疏注意力再砍价",
    architecture: "9-29 先发 V3.2-Exp：首发 DeepSeek Sparse Attention（DSA），细粒度选择性计算注意力，长上下文开销大降而精度持平；参数不变（685B/37B）。12-01 正式版转向 reasoning-first、引入可扩展 RL 框架；MIT。DSA 是 V4 混合注意力的直接前身。",
    archClaim: "事实",
    capability: "Exp 各基准与 Terminus 持平（验证 DSA 无损）；正式版官方口径对标 GPT-5，高算力变体 V3.2-Speciale 达 2025 IMO/IOI 金牌线。",
    capClaim: "事实",
    price: "$0.28（miss）/$0.028（hit）/$0.42 out——随 Exp 发布 API 直降 50%+",
    compute: "DSA 把长上下文注意力从 O(L²) 降为稀疏选择，官方明示降价空间即来自算力节省；全量 GPU-hours 未单独披露。",
    computeClaim: "推理",
  },
  {
    vendor: "deepseek", date: "2026-04", name: "DeepSeek V4 Preview (Pro/Flash)", tier: "major", preview: true,
    headline: "1.6T 开源之最，联手昇腾",
    architecture: "V4-Pro：1.6T 总参/49B 激活（61 层、hidden 7168、每 MoE 层 384 路由+1 共享专家激活 6），开源史上最大权重；V4-Flash：284B/13B。CSA+HCA 混合注意力（token-wise 压缩+DSA 演进）：1M 上下文下 Pro 单 token 推理 FLOPs 仅为 V3.2 的 27%、KV cache 10%。FP8+FP4 QAT，1M 上下文，MIT。",
    archClaim: "事实",
    capability: "SWE-bench Verified 80.6%、LiveCodeBench 93.5%、Codeforces 3206（相当于人类选手第 23 名）；开源模型世界知识第一，仅次于 Gemini-3.1-Pro。",
    capClaim: "事实",
    price: "Pro $0.435/$0.87（hit $0.0036）；Flash $0.14/$0.28——约为 GPT-5.4 输出价 1/9",
    compute: "报告：Pro 预训练 33T/Flash 32T tokens；Muon 优化器+mHC+Anticipatory Routing 保证 1.6T 规模零 loss spike；官方确认 EP 并行方案在 NVIDIA GPU 与 Ascend NPU 双平台验证，Reuters 报道 Flash 部分训练使用华为芯片（芯片分工细节未经官方确认）——国产替代叙事的最强单点证据。",
    computeClaim: "事实",
  },

  // ===== 阿里 Qwen =====
  {
    vendor: "qwen", date: "2024-02", name: "Qwen 1.5", tier: "minor",
    headline: "全尺寸开源矩阵起步",
    architecture: "0.5B–72B 六个 dense 尺寸统一发布（后补 32B/110B 及首个 MoE 试水），全系 32K 上下文、统一 chat 模板。通义千问许可（尚未转 Apache）。",
    archClaim: "事实",
    capability: "72B 在 MT-Bench/Arena 位列当时最强开源之列，但与 GPT-4 仍有明显差距。意义在确立「全尺寸+快节奏」开源打法。",
    capClaim: "事实",
    price: "开源自建（Qwen license）+ 阿里云 API",
    compute: "训练 token 数与 GPU 规模未披露（阿里全系从不公布 GPU-hours）。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2024-06", name: "Qwen 2", tier: "minor",
    headline: "旗舰首转 Apache 2.0",
    architecture: "0.5B–72B dense + 57B-A14B MoE；全系换用 GQA；72B 支持 128K 上下文。除 3B 外主力尺寸首次转 Apache 2.0，扫清商用障碍。",
    archClaim: "事实",
    capability: "Qwen2-72B MMLU 84.2、HumanEval 64.6，超越 Llama3-70B 坐上开源第一梯队；27+ 语言成差异化卖点。",
    capClaim: "事实",
    price: "开源自建（Apache 2.0）+ 阿里云 API",
    compute: "72B 预训练约 7T tokens（官方）；GPU 集群未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2024-09", name: "Qwen 2.5", tier: "major",
    headline: "18T tokens 开源全家桶",
    architecture: "0.5B–72B 七个尺寸 + Coder + Math 专项线；预训练语料从 7T 扩至 18T tokens；GQA、YaRN 扩展至 128K 上下文。除 3B/72B 外全系 Apache 2.0。",
    archClaim: "事实",
    capability: "72B-Instruct 部分基准追平 Llama-3.1-405B；Coder-32B 登顶开源代码模型。此后 Qwen 成为全球 finetune 生态第一基座（HF 衍生模型数第一），R1 蒸馏系也以 2.5 为底。",
    capClaim: "事实",
    price: "开源自建 + 阿里云 API",
    compute: "预训练 18T tokens（官方技术报告）；GPU-hours 未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2025-03", name: "QwQ-32B", tier: "major",
    headline: "32B 单卡跑出 R1 级推理",
    architecture: "32B dense（非 MoE），基于 Qwen2.5-32B 两阶段大规模 RL：先数学/代码（准确率验证器+代码沙箱结果奖励），再通用能力。131K 上下文，Apache 2.0。",
    archClaim: "事实",
    capability: "AIME24 79.5、LiveCodeBench 63.4，逼近 671B 的 R1，证明中尺寸 dense+RL 的推理性价比路线成立；量化后单张 24GB 消费卡可跑——本地部署推理模型的分水岭。",
    capClaim: "事实",
    price: "开源自建（Apache 2.0）",
    compute: "RL 训练算力未披露；基座为 18T tokens 的 Qwen2.5-32B。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2025-04", name: "Qwen 3", tier: "major",
    headline: "36T tokens 混合思考开源",
    architecture: "旗舰 235B-A22B（128 专家激活 8）+ 30B-A3B 两款 MoE，另 0.6B–32B 六款 dense；单模型 thinking/non-thinking 可切换并支持思考预算；36T tokens、119 种语言；Apache 2.0。注：2025-07 的 2507 版放弃单模型混合思考、拆分 Instruct/Thinking 两线并大幅提分。",
    archClaim: "事实",
    capability: "235B-A22B AIME24 85.7，整体对标 o3-mini/Gemini-2.5-Pro 档。9 月另有 1T+ 闭源 Qwen3-Max。",
    capClaim: "事实",
    price: "开源自建（Apache 2.0）+ 阿里云 API",
    compute: "预训练 36T tokens（官方，较 Qwen2.5 翻倍）；GPU 集群未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2025-09", name: "Qwen3-Next-80B-A3B", tier: "major",
    headline: "线性注意力混合架构试验田",
    architecture: "80B 总参/3.9B 激活的极稀疏 MoE。核心创新是 3:1 混合注意力——每 3 层 Gated DeltaNet（线性注意力）配 1 层 Gated Attention，另加 MTP、zero-centered layernorm；原生 262K 上下文，1M tokens KV 仅 ~25GB（约纯 transformer 1/4）。Apache 2.0。",
    archClaim: "事实",
    capability: "官方：以 Qwen3-32B 约 10% 的训练成本超越其表现，长上下文推理吞吐 10x。架构验证成功后被 Qwen3.5 旗舰全盘继承，Kimi Linear 亦跟进同款 3:1 配比——单模型影响力远超其规模档位。",
    capClaim: "事实",
    price: "开源自建（Apache 2.0）",
    compute: "预训练 15T tokens（36T 语料子集）；官方称总训练成本仅为 Qwen3-32B 约 10%。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2026-02", name: "Qwen 3.5 (397B-A17B)", tier: "major",
    headline: "首个原生多模态开源旗舰",
    architecture: "397B 总参/17B 激活；继承 Qwen3-Next 混合架构（Gated DeltaNet 线性注意力+标准注意力），60 层、512 专家（10 路由+1 共享）、MTP。首个原生视觉输入的 Qwen 开源旗舰（VL 与文本线合并），201 种语言，262K 上下文（API 版 1M）。Apache 2.0，02-16 发布。",
    archClaim: "事实",
    capability: "AA Intelligence Index 45，开源第 3；官方称约 80% 基准超 GPT-5.2/Claude 4.5 Opus/Gemini 3 Pro，指令跟随（IFBench）最强。混合注意力使推理较前代快 8x、成本约 -60%。",
    capClaim: "事实",
    price: "开源 Apache 2.0；Qwen3.5-Plus API 约 $0.26–0.40/$1.56–2.40（两渠道口径不一）",
    compute: "训练 token 数与 GPU 规模未披露；BF16 自建需 ~800GB VRAM，FP8 减半。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2026-04", name: "Qwen 3.6 (27B/35B-A3B)", tier: "minor",
    headline: "27B dense 逆袭 397B 旗舰",
    architecture: "两款开源：35B-A3B MoE 与 27B dense。27B 沿用 Gated DeltaNet+自注意力混合架构，新增 Thinking Preservation，支持文本/图像/视频输入；262K 上下文（YaRN 可扩 ~1M）；Apache 2.0。其上另有闭源 Qwen3.6-Max-Preview——阿里旗舰闭源的信号弹。",
    archClaim: "事实",
    capability: "27B 自报 SWE-bench Verified 77.2 反超 Qwen3.5-397B（76.2），Terminal-Bench 2.0 59.3 追平 Claude 4.5 Opus（自家 scaffold 口径，第三方验证有限）；Q4 量化单张 RTX 4090 可跑。",
    capClaim: "推理",
    price: "开源自建（Apache 2.0）",
    compute: "训练细节未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "qwen", date: "2026-05", name: "Qwen3.7-Max", tier: "major",
    headline: "闭源转身，Agent 旗舰",
    architecture: "闭源 API-only，参数未披露（推理：大概率延续稀疏 MoE+混合注意力路线）——Qwen 旗舰首次完全不放权重，开源策略的分水岭。1M 上下文、65K 输出；定位 Agent 时代：官方演示 35 小时全自主 kernel 优化、1000+ 工具调用。05-19 发布。",
    archClaim: "推理",
    capability: "Terminal-Bench 2.0-Terminus 69.7 居首、GPQA Diamond 92.4、SWE-bench Verified 80.4、HMMT 2026Feb 97.1（自家评测表，部分经第三方验证）；对标 GPT-5.5/Claude Opus 4.7 档，主打 capability-per-dollar。",
    capClaim: "事实",
    price: "$2.5/$7.5，cached input $0.25（90% 缓存折扣，利好长上下文 Agent）",
    compute: "训练算力完全未披露（闭源）；推测阿里云自有集群。",
    computeClaim: "推测",
  },

  // ===== 月之暗面 Kimi =====
  {
    vendor: "kimi", date: "2025-01", name: "Kimi k1.5", tier: "major",
    headline: "RL 长思维链首份报告",
    architecture: "闭源多模态模型，参数未披露；与 R1 同日（1-20）发布技术报告，核心是 RL scaling 方法论：long-CoT RL、long2short 蒸馏、partial rollout 长上下文 RL 训练系统；128K 上下文。",
    archClaim: "事实",
    capability: "AIME 77.5、MATH-500 96.2、Codeforces 94 百分位，long-CoT 版对标 o1。与 R1 并列「中国推理模型双响」，但闭源使声量被 R1 盖过。",
    capClaim: "事实",
    price: "闭源，Kimi API/App",
    compute: "训练算力与数据规模均未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "kimi", date: "2025-07", name: "Kimi K2", tier: "major",
    headline: "1T 开源，Agentic 元年",
    architecture: "1T 总参/32B 激活 MoE：61 层、384 专家激活 8、MLA 注意力、160K 词表、128K 上下文。Modified MIT（月活 >1 亿或月收 >$2000 万需展示 Kimi K2 标识）。Base+Instruct 双 checkpoint，定位 open agentic intelligence。",
    archClaim: "事实",
    capability: "non-thinking 模式 SWE-bench Verified 65.8、Tau2-bench 66.1、GPQA 75.1，逼近 Claude 4 Opus/Sonnet；2025-07 Arena 开源第 1、总榜第 5。",
    capClaim: "事实",
    price: "$0.60/$2.50（cache hit $0.15）；开源自建 Modified MIT",
    compute: "技术报告（arXiv 2507.20534）：预训练 15.5T tokens；MuonClip 优化器（qk-clip 压制注意力 logit 爆炸）实现全程零 loss spike——万亿参数训练稳定性的公开配方。GPU 集群未官方披露。",
    computeClaim: "事实",
  },
  {
    vendor: "kimi", date: "2025-11", name: "Kimi K2 Thinking", tier: "major",
    headline: "HLE 开源首超 GPT-5",
    architecture: "沿用 K2 架构（1T/32B、384 专家、MLA），上下文扩至 256K；原生 INT4 QAT——量化感知训练直接产出 INT4 权重（~600GB），推理 2x 提速近无损；可自主连续执行 200–300 次工具调用。Modified MIT。",
    archClaim: "事实",
    capability: "HLE（带工具）44.9 与 BrowseComp 60.2 均创当时 SOTA；Heavy Mode（8 路并行推理）HLE 超 GPT-5 约 9 分——开源模型首次在旗舰推理基准正面越线闭源。",
    capClaim: "事实",
    price: "$0.60/$2.50；2026-05-25 已 EOL，导流 K2.5/K2.6",
    compute: "CNBC 引述知情人称训练成本 $4.6M，未经独立验证；基于 K2 基座续训+RL。",
    computeClaim: "推测",
  },
  {
    vendor: "kimi", date: "2026-01", name: "Kimi K2.5", tier: "major",
    headline: "原生视觉+百智能体集群",
    architecture: "1T/32B、384 专家、MLA 骨架不变，新增原生视觉：15T 图文混合 tokens 从头早融合训练（10% 视觉占比优于后期嫁接），提出 zero-vision SFT、视觉 RL 反哺文本（GPQA 84.3→86.4）。256K 上下文，Modified MIT，1-27「静默发布」。",
    archClaim: "事实",
    capability: "OCRBench 92.3/MathVista 90.1/InfoVQA 92.6 含闭源在内全模型第一；HLE-full 带工具 50.2 超 GPT-5.2（45.5）；Agent Swarm 可编排 100 个子智能体，BrowseComp 60.6→78.4、耗时降 3–4.5x。",
    capClaim: "事实",
    price: "$0.60/$2.50–3.00（口径不一，cache hit ~$0.10）；开源自建",
    compute: "15T 图文混合 tokens 预训练（官方）；GPU 集群未披露。",
    computeClaim: "事实",
  },
  {
    vendor: "kimi", date: "2026-04", name: "Kimi K2.6", tier: "major",
    headline: "300 智能体群，13 小时编码",
    architecture: "1T/32B、61 层、384 专家、MLA 保持；256K 上下文，新增 400M 参数 MoonViT 视觉编码器（原生图像+视频输入）；四变体分发（Instant/Thinking/Agent/Agent Swarm），Swarm 从 K2.5 的 100 子智能体×1500 步扩到 300×4000 步。Modified MIT，4-20 发布。",
    archClaim: "事实",
    capability: "SWE-bench Pro 58.6 超 GPT-5.4（57.7）/Opus 4.6（53.4），SWE-bench Verified 80.2，HLE 带工具 54.0 居首，Swarm 模式 BrowseComp 86.3；AA 总榜第 4、开源第 1；官方演示 13 小时连续编码（无第三方复现）。",
    capClaim: "事实",
    price: "$0.95/$4.00（cache hit ~$0.16）；开源自建",
    compute: "训练规模未披露；基于 K2 系基座持续迭代。Moonshot 同期传出赴港 IPO 与 ~$10 亿新融资。",
    computeClaim: "推理",
  },
  {
    vendor: "kimi", date: "2026-06", name: "Kimi K2.7-Code", tier: "minor",
    headline: "编码特化，Opus 1/5 价",
    architecture: "1T/32B、384 专家、256K 上下文，支持文本/图像/视频输入；强制 thinking 模式（关闭即 API 报错），采样固定 temp 1.0；推理 token 用量较 K2.6 省约 30%。权重 595GB 上 HF，Modified MIT，6-12 发布——一年内第五次大版本。",
    archClaim: "事实",
    capability: "自报 Kimi Code Bench v2 较 K2.6 +21.8%、MCPMark Verified 81.1 超 Opus 4.8（76.4）；发布初无独立 SWE-bench 分数，VentureBeat 报道从业者对官方数字存疑；AA Intelligence Index 42。",
    capClaim: "推理",
    price: "$0.95（cache hit $0.19）/$4.00（高速档 $8）；约为 Claude Opus 4.8 的 1/5–1/6",
    compute: "训练细节未披露。",
    computeClaim: "事实",
  },
]
