// OpenAI + Anthropic 发布数据（经独立研究 agent 多源核实，2026-07-06）
import type { Release } from "./data"

export const RELEASES_US: Release[] = [
  // ===== OpenAI =====
  {
    vendor: "openai", date: "2024-05", name: "GPT-4o", tier: "major",
    headline: "原生全模态统一模型",
    architecture: "首个端到端原生多模态模型，文本/音频/图像在同一网络内处理，语音平均延迟约 320ms。参数量未公开；128K 上下文，输出上限后期提至 16K。官方未披露内部结构。",
    archClaim: "事实",
    capability: "MMLU 88.7%、HumanEval 90.2%、GPQA 53.6%，发布时登顶 LMArena。多模态（视觉+语音）当时业界最强，但无深度推理能力，复杂数学/科学题仍是短板。",
    capClaim: "事实",
    price: "$5/$15 → 2024-08 降至 $2.5/$10（vs GPT-4 Turbo $10/$30 腰斩）；2024-07 配套 GPT-4o mini $0.15/$0.60 取代 3.5 Turbo",
    compute: "训练算力与成本未披露，Microsoft Azure 集群完成。相比 GPT-4 更强调推理成本效率而非规模扩张，外界推测参数量小于 GPT-4。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2024-09", name: "o1-preview / o1-mini", tier: "major",
    headline: "推理范式：测试时计算",
    architecture: "通过大规模 RL 训练模型生成隐藏思维链再作答，开创 test-time compute 范式；推理 token 对用户不可见但计费。128K 上下文。正式版 o1（含 o1-pro）2024-12 发布。",
    archClaim: "事实",
    capability: "o1-preview AIME 2024 44.6%，正式版 o1 达 74.4%（共识投票 83.3%）；GPQA Diamond 78.3%，首次超过人类 PhD 专家水平；Codeforces 89 百分位。开启推理模型竞赛，但速度慢、不支持工具。",
    capClaim: "事实",
    price: "$15/$60，推理 token 按输出计费，实际单位任务成本远高于 GPT-4o（$2.5/$10）",
    compute: "训练 FLOPs 未披露；官方公开了性能随训练/推理算力对数线性提升的 scaling 曲线。推理阶段算力消耗数倍于传统模型。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2025-01", name: "o3-mini", tier: "minor",
    headline: "低价推理模型普及",
    architecture: "小型推理模型，首次提供 low/medium/high 三档 reasoning effort；200K 上下文、100K 输出；支持函数调用与结构化输出，不支持视觉。推断为蒸馏/小参数版本。",
    archClaim: "推理",
    capability: "high 档 AIME 2024 87.3%、GPQA Diamond 79.7%、Codeforces Elo ~2130，以约 1/14 价格逼近 o1 水平。免费版 ChatGPT 首次可用推理模型。",
    capClaim: "事实",
    price: "$1.10/$4.40，较 o1-mini（$3/$12）降 63%，仅为 o1 的 7%",
    compute: "训练算力未披露。定位即「把 o1 级推理做便宜」，推断以蒸馏+小模型 RL 为主。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2025-02", name: "GPT-4.5 (Orion)", tier: "major", preview: true,
    headline: "最大预训练模型绝唱",
    architecture: "官方称其「最大、知识最广」的模型，纯预训练扩张路线、无推理链；128K 上下文。官方确认训练横跨多个 Azure 数据中心。后被 GPT-5 路线取代，2025-07 从 API 下线。",
    archClaim: "事实",
    capability: "SimpleQA 62.5%、幻觉率显著低于 4o；GPQA 71.4%；但 AIME 仅 36.7%，数学明显弱于同期推理模型。卖点是情商、写作与「品味」，实质证明纯 scaling 收益递减。",
    capClaim: "事实",
    price: "$75/$150，为 GPT-4o 输入价 30 倍，史上最贵通用模型；5 个月即弃",
    compute: "官方确认跨多数据中心训练；外界普遍估计有效训练算力约为 GPT-4 的 10 倍量级（第三方估计）。单位算力性价比过低是退场主因。闭源。",
    computeClaim: "推理",
  },
  {
    vendor: "openai", date: "2025-04", name: "GPT-4.1 / mini / nano", tier: "minor",
    headline: "1M 上下文开发者专线",
    architecture: "API 专供（不进 ChatGPT）的非推理系列，三档规格；上下文首次扩到 1M token，输出 32K。mini/nano 推断为蒸馏小型化，mini 延迟约为 4o 一半。",
    archClaim: "推理",
    capability: "SWE-bench Verified 54.6%（较 4o 的 33% 大幅提升）、MMLU 90.2%、Video-MME 72.0%。定位编码与指令遵循的高性价比主力。",
    capClaim: "事实",
    price: "$2/$8；mini $0.4/$1.6；nano $0.1/$0.4——对 4o（$2.5/$10）降价约 26%",
    compute: "训练算力未披露；产品逻辑是用更小算力复刻并超越 4o 的开发者场景能力。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2025-04", name: "o3 & o4-mini", tier: "major",
    headline: "工具调用融入推理链",
    architecture: "首批在思维链内原生调用全套工具（搜索/Python/图像分析）的推理模型，可「用图像思考」；200K 上下文、100K 输出。o3 于 2024-12 预告、2025-04-16 上线。",
    archClaim: "事实",
    capability: "o3：AIME 2024 91.6%、GPQA 83.3%、SWE-bench Verified 69.1%、Codeforces Elo 2706；2024-12 预告时 ARC-AGI-1 半私有集 75.7%（高算力 87.5%）。o4-mini AIME 2025 92.7%。",
    capClaim: "事实",
    price: "o3 $10/$40，2025-06 降 80% 至 $2/$8；o4-mini $1.10/$4.40",
    compute: "训练 FLOPs 未披露；ARC Prize 披露 o3 高算力配置单题推理成本达数千美元，测试时算力消耗史无前例。据此推断 RL 后训练算力已接近预训练量级。闭源。",
    computeClaim: "推理",
  },
  {
    vendor: "openai", date: "2025-08", name: "GPT-5", tier: "major",
    headline: "统一路由推理系统",
    architecture: "官方定义为「统一系统」：实时 router 在快速模型与深度推理模型间自动调度；API 提供 gpt-5/mini/nano，400K 总上下文（272K 输入+128K 输出），新增 minimal 推理档与 verbosity 参数。",
    archClaim: "事实",
    capability: "SWE-bench Verified 74.9%、AIME 2025 无工具 94.6%、Aider Polyglot 88%；官方称开启思考时事实性错误较 o3 少约 80%。综合登顶但发布口碑翻车（路由不稳、「变笨」争议）。",
    capClaim: "事实",
    price: "$1.25/$10（mini $0.25/$2、nano $0.05/$0.4）——直接压到 Claude Opus 4.1（$15/$75）约 1/10，掀起价格战",
    compute: "训练算力未披露，训练于 Azure 及新建超算集群；无公认第三方 FLOPs 估计。合成数据+RL 后训练占比被普遍认为显著上升。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2025-11", name: "GPT-5.1", tier: "minor",
    headline: "自适应推理+人格化",
    architecture: "Instant/Thinking 双变体均引入 adaptive reasoning：按任务难度动态决定思考深度，另有 no-reasoning 模式；410K 上下文、128K 输出；配套 gpt-5.1-codex。API 新增最长 24 小时扩展 prompt caching。",
    archClaim: "事实",
    capability: "官方称 AIME 2025 与 Codeforces 显著提升、SWE-bench Verified 亦有改进（未披露统一数字）；简单任务提速、复杂任务更深思。ChatGPT 侧主打 8 种人格。",
    capClaim: "事实",
    price: "与 GPT-5 持平：$1.25/$10；24h 缓存进一步压低多轮 agent 成本",
    compute: "同代基座的后训练迭代，推断增量算力远小于代际升级。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2026-03", name: "GPT-5.4", tier: "major",
    headline: "推理与 Codex 栈合一",
    architecture: "承接 GPT-5.2（2025-12）与 GPT-5.3-Codex（2026-02，首个融合 Codex 与 GPT-5 训练栈的统一模型）：单一前沿模型覆盖推理/编码/办公 agent，1M 上下文，5 档 reasoning effort（none→xhigh）。",
    archClaim: "事实",
    capability: "Terminal-Bench 2.0 75.1%（GPT-5.5 发布时官方对比基线）；第三方汇总其计算机使用约 75%。同批 GPT-5.3 Instant 承担 ChatGPT 默认；3-11 起 GPT-5.1 全系退役。",
    capClaim: "事实",
    price: "$2.50/$15（mini $0.75/$4.50、nano $0.20/$1.25），较 GPT-5.1 的 $1.25/$10 翻倍，结束一年低价期",
    compute: "训练算力未披露；Stargate 首批站点 2025-26 陆续投运，推断 5.x 中后段开始使用新集群，无官方归属确认。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2026-04", name: "GPT-5.5 (Spud)", tier: "major",
    headline: "长程智能体执行飞跃",
    architecture: "04-23 上线 ChatGPT/Codex、次日开放 API。1M 上下文；输入超 272K 后全程按 2x 输入/1.5x 输出计费。含 GPT-5.5 Pro；GPT-5.5 Instant 于 05-05 成为免费默认。",
    archClaim: "事实",
    capability: "Terminal-Bench 2.0 82.7%（自 5.4 的 75.1% 跃升）、ARC-AGI-2 85.0% 为公开最佳；但 SWE-bench Pro 仅 58.6%，落后 Claude Opus 4.7/4.8；GDPval-AA 落后 Opus 4.8 达 121 Elo。主打「跨工具跑完整个任务」。",
    capClaim: "事实",
    price: "$5/$30（Pro $30/$180），较 5.4 翻倍；官方辩称输出 token 少 40%、有效涨幅约 20%",
    compute: "训练算力未披露；官方称同等延迟下智能提升。Stargate/Azure 新集群支撑为合理推断。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "openai", date: "2026-06", name: "GPT-5.6 Sol / Terra / Luna", tier: "major", preview: true,
    headline: "三层级命名体系转向",
    architecture: "06-26 起限量预览（约 20 家受邀机构，API/Codex，不进 ChatGPT）；此前依 06-02 行政令向美政府备案。命名改制：数字代际+Sol/Terra/Luna 固定档位，另有更高算力的 Sol Ultra 模式。新增显式 cache breakpoint。",
    archClaim: "事实",
    capability: "官方称 Sol 全面超越 GPT-5.5、Terra 与 GPT-5.5 性能相当但价格减半；公开基准数字尚未发布（预览期）。7 月起 Sol 将登陆 Cerebras，最高 750 tok/s。",
    capClaim: "事实",
    price: "预览价：Sol $5/$30、Terra $2.5/$15、Luna $1/$6；缓存写 1.25x、读 -90%；GA 时或调整",
    compute: "训练算力未披露。Terra「GPT-5.5 性能半价」指向蒸馏+推理效率的代际红利；Cerebras 合作说明推理硬件多元化。闭源。",
    computeClaim: "推测",
  },

  // ===== Anthropic =====
  {
    vendor: "anthropic", date: "2024-03", name: "Claude 3 (Opus/Sonnet/Haiku)", tier: "major",
    headline: "三档产品线首超 GPT-4",
    architecture: "确立 Opus/Sonnet/Haiku 三档产品结构；全系 200K 上下文（特定客户可至 1M），首次全系支持视觉输入。参数量与内部结构未披露。",
    archClaim: "事实",
    capability: "Opus：MMLU 86.8%、GPQA 50.4%、HumanEval 84.9%，是首个在 LMArena 榜首超越 GPT-4 系的非 OpenAI 模型。Haiku 以近实时速度覆盖轻量场景。",
    capClaim: "事实",
    price: "Opus $15/$75、Sonnet $3/$15、Haiku $0.25/$1.25",
    compute: "训练算力未披露；Dario Amodei 同期访谈称当代前沿模型训练成本约 1 亿美元量级（转述）。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2024-06", name: "Claude 3.5 Sonnet", tier: "major",
    headline: "中档价格旗舰性能",
    architecture: "以 Sonnet 档价格交付超越 Claude 3 Opus 的性能，2 倍于 Opus 的速度；200K 上下文。配套发布 Artifacts 交互界面。参数未披露。",
    archClaim: "事实",
    capability: "GPQA 59.4%、HumanEval 92.0%；内部 agentic coding 评测 64%（Claude 3 Opus 为 38%）。此后一年成为开发者默认编码模型，奠定 Anthropic 编码心智。",
    capClaim: "事实",
    price: "$3/$15，与 Claude 3 Sonnet 持平——旗舰性能降到中档价",
    compute: "训练算力未披露；「中档价超旗舰」说明训练效率（数据/方法）代际提升，而非单纯堆算力。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2024-10", name: "Claude 3.5 Sonnet v2 + 3.5 Haiku", tier: "minor",
    headline: "计算机使用首发",
    architecture: "3.5 Sonnet 升级版首发 computer use 公测 API：模型直接看屏幕截图、移动光标点击输入，业界首个通用 GUI agent 能力。3.5 Haiku 为新一代小模型。",
    archClaim: "事实",
    capability: "Sonnet v2 SWE-bench Verified 49.0%（自 33% 提升）、OSWorld 14.9%（业界当时最高）；3.5 Haiku SWE-bench Verified 40.6%，多项基准超上代旗舰 Claude 3 Opus。",
    capClaim: "事实",
    price: "Sonnet v2 维持 $3/$15；3.5 Haiku $0.8/$4，较 3 Haiku 涨 3.2 倍引发争议",
    compute: "训练算力未披露。Haiku 涨价隐含小模型训练成本（蒸馏+数据）已非「便宜档」逻辑。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2025-02", name: "Claude 3.7 Sonnet", tier: "major",
    headline: "首个混合推理模型",
    architecture: "业界首个「混合推理」模型：同一模型可即时应答或开启 extended thinking，思考预算由 token 数精确控制；200K 上下文，输出上限提至 64K（beta 128K）。同日发布 Claude Code CLI。",
    archClaim: "事实",
    capability: "SWE-bench Verified 62.3%（自定义脚手架 70.3%），当时第一；TAU-bench retail 81.2%。与 Claude Code 组合开启 agentic coding 商业爆发。",
    capClaim: "事实",
    price: "$3/$15 不变，思考 token 计入输出",
    compute: "Dario Amodei 播客访谈称 3.7 训练成本「几千万美元」量级——前沿能力主要来自后训练方法而非算力堆叠（转述自公开访谈）。闭源。",
    computeClaim: "事实",
  },
  {
    vendor: "anthropic", date: "2025-05", name: "Claude 4 (Opus 4 & Sonnet 4)", tier: "major",
    headline: "长时程智能体编码",
    architecture: "extended thinking 中可交替调用工具；引入记忆文件机制支持长任务连续性；200K 上下文。Opus 4 是 Anthropic 首个按 ASL-3 安全等级部署的模型。",
    archClaim: "事实",
    capability: "SWE-bench Verified：Opus 4 72.5%（并行算力 79.4%）、Sonnet 4 72.7%；Terminal-bench 43.2%。Rakuten 实测 Opus 4 连续自主编码约 7 小时，长时程 agent 首获客户背书。",
    capClaim: "事实",
    price: "Opus 4 $15/$75、Sonnet 4 $3/$15；2025-08 Opus 4.1 增量升级（SWE-bench 74.5%）价格不变",
    compute: "训练算力未披露；ASL-3 启用暗示能力/算力跨过内部阈值。AWS Trainium 与 GCP TPU 混合训练为公开合作方向，具体归属未确认。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2025-09", name: "Claude Sonnet 4.5", tier: "major",
    headline: "30 小时自主编码",
    architecture: "面向长时程 agent 优化：API 新增 context editing（自动清理旧工具调用）与 memory tool；200K 上下文（1M beta）、64K 输出。checkpoint 等配套进入 Claude Code。",
    archClaim: "事实",
    capability: "SWE-bench Verified 77.2%（并行算力 82.0%）登顶；OSWorld 61.4%（4 个月前 Sonnet 4 为 42.2%）；官方称可保持 30+ 小时任务专注（Claude 4 约 7 小时）。",
    capClaim: "事实",
    price: "$3/$15 不变，中档价打旗舰",
    compute: "训练算力未披露。同期 AWS Project Rainier（数十万片 Trainium2）开始投运，外界推断 4.5 代起部分使用该集群，无官方确认。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2025-10", name: "Claude Haiku 4.5", tier: "minor",
    headline: "小模型逼近旗舰编码",
    architecture: "首个支持 extended thinking 的 Haiku；200K 上下文。定位：5 个月前的旗舰（Sonnet 4）编码水平以小模型规格交付，速度 2 倍以上。",
    archClaim: "事实",
    capability: "SWE-bench Verified 73.3%，与 Sonnet 4（72.7%）持平；OSWorld 50.7%。适合多 agent 编排的执行层：Sonnet 4.5 规划+多个 Haiku 4.5 并行执行成为官方推荐模式。",
    capClaim: "事实",
    price: "$1/$5，为 Sonnet 4.5 的 1/3",
    compute: "训练算力未披露；「5 个月把旗舰能力蒸到小模型」反映蒸馏管线的代际速度。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2025-11", name: "Claude Opus 4.5", tier: "major",
    headline: "旗舰降价三分之二",
    architecture: "首次引入 effort 参数（控制思考与输出深度）；200K 上下文、64K 输出。定价体系重构是本代最大结构性变化。",
    archClaim: "事实",
    capability: "SWE-bench Verified 80.9%，首个破 80% 的模型；ARC-AGI-2 37.6%（当时前沿推理最佳档）；官方称其在内部工程师招聘笔试中超过所有人类候选人。对 GPT-5.1、Gemini 3 Pro 全面反击。",
    capClaim: "事实",
    price: "$5/$25，较 Opus 4.1 的 $15/$75 直降 67%——对 GPT-5 价格战的正面回应",
    compute: "训练算力未披露。同期基础设施：Project Rainier 近 50 万片 Trainium2 已投运（2025-10 官方披露），并宣布采购最高 100 万片 Google TPU；训练归属为推断。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2026-02", name: "Claude Opus 4.6 (+ Sonnet 4.6)", tier: "major",
    headline: "1M 上下文进旗舰",
    architecture: "adaptive thinking 取代固定思考预算（模型自主决定何时/想多少，effort 四档）；1M 上下文（beta）、128K 输出。两周后 Sonnet 4.6（02-17，$3/$15）以近旗舰性能跟进。",
    archClaim: "事实",
    capability: "SWE-bench Verified 80.8%、Terminal-Bench 2.0 65.4%、OSWorld 72.7% 均为当时最高；1M 长上下文 MRCR v2 8-needle 76%（Sonnet 4.5 仅 18.5%）；HLE 带工具 53.0%。",
    capClaim: "事实",
    price: "$5/$25 不变；1M 长上下文档另有溢价",
    compute: "训练算力未披露；1M 上下文旗舰化+adaptive thinking 指向推理算力管理成为竞争焦点。Rainier/TPU 双供应链持续扩张为公开事实。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2026-05", name: "Claude Opus 4.8", tier: "major",
    headline: "并行子代理+快模式",
    architecture: "承接 Opus 4.7（04-16：SWE-bench Verified 87.6%、新 tokenizer 同文本最多 +35% token、新增 xhigh 档）：4.8 于 05-28 发布，间隔仅 41 天。1M 上下文默认、128K 输出；配套 Claude Code Dynamic Workflows 可派生数百个并行 subagent。",
    archClaim: "事实",
    capability: "SWE-bench Verified 88.6%、SWE-bench Pro 69.2%（领先 GPT-5.5 的 58.6% 逾 10pt）、Terminal-Bench 2.1 74.6%、USAMO 2026 96.7%、OSWorld 83.4%；GDPval-AA 1890，领先 GPT-5.5 121 Elo。官方称放过自写代码缺陷的概率降至 1/4。",
    capClaim: "事实",
    price: "$5/$25 不变；fast mode $10/$50（约 2.5x 速度），较 Opus 4.7 fast mode 的 $30/$150 降 3 倍",
    compute: "训练算力未披露；官方明示 4.8 位于 Opus 4.7 与未公开 Mythos Preview 之间，即内部已有更大模型压阵。41 天迭代节奏指向持续后训练而非重新预训练。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2026-06", name: "Claude Fable 5 (& Mythos 5)", tier: "major",
    headline: "Mythos 级智能体旗舰",
    architecture: "06-09 发布，首个 Mythos 级（高于 Opus 档）公开模型：Fable 5 与限量版 Mythos 5 同底座，区别仅在 Fable 附加网络安全/生物/反蒸馏三类安全分类器（≥95% 会话不触发，触发时回退 Opus 4.8）。1M 上下文默认、128K 输出；adaptive thinking 为唯一思考模式；知识截止 2026-01。",
    archClaim: "事实",
    capability: "官方口径 SWE-bench Pro 80.3%（Opus 4.8 为 69.2%、GPT-5.5 为 58.6%）、Terminal-Bench 2.1 88.0%、FrontierCode Diamond 29.3%（GPT-5.5 仅 5.7%）；第三方 Vals 榜 SWE-bench Verified 95.0%；AA 指数 65（GPT-5.5 为 61）。Stripe 称 5000 万行 Ruby 迁移由两个月压缩到一天。06-12 因美出口管制指令停服，07-01 加装新分类器后恢复。",
    capClaim: "事实",
    price: "$10/$50，为 Opus 4.8 的 2 倍；06-23 起从订阅移出、改按 usage credits 计费",
    compute: "规模与训练算力未披露；Simon Willison 等推测其可能是迄今任何厂商发布的最大模型（第三方推测）。Rainier（Trainium2 百万片级）与 Google TPU 协议是同期算力底座，训练归属为推断。闭源。",
    computeClaim: "推测",
  },
  {
    vendor: "anthropic", date: "2026-06", name: "Claude Sonnet 5", tier: "major",
    headline: "Opus 级性能 Sonnet 价",
    architecture: "06-30 发布，接替 Sonnet 4.6。1M 上下文、128K 输出；effort 五档（low→x-high）；新 tokenizer 同文本 token 数约 1.0-1.35 倍；知识截止 2026-01。Free/Pro 默认模型。",
    archClaim: "事实",
    capability: "SWE-bench Pro 63.2%（Sonnet 4.6 为 58.1%，逼近 Opus 4.8 的 69.2%），agentic 推理/工具使用/知识工作全面超上代。",
    capClaim: "事实",
    price: "介绍价 $2/$10（至 2026-08-31），此后 $3/$15。注意：tokenizer 变化使英文/代码场景实际成本接近「名义降价被抵消」",
    compute: "训练算力未披露；「旗舰性能下放中档+介绍价」延续以训练效率换市占的路线。闭源。",
    computeClaim: "推测",
  },
]
